### ISSUE TITLE
Failed to flash arm trusted firmware to Jetson TX2

### ISSUE THREAD

**Issue by danielRep** [bao-project/bao-demos#51]
Hi,

I followed [the instructions from bao-demos](https://github.com/bao-project/bao-demos/tree/master/platforms/tx2) to install bao on Jetson TX2. However, I stuck at the step to flash arm trusted firmware to Jetson TX2. After the flash command started, it hung for almost an hour. I had nothing to do but interrupt the process.

I am seeking for help to successfully flash the firmware. The followings are some information that might be helpful.

I'm sure the board was in recovery mode.
![image](https://github.com/bao-project/bao-hypervisor/assets/24734750/708f62e4-6dc7-427f-897a-67ed72699cf4)

During the flashing, it showed a message `BootRom is not running`.
![image](https://github.com/bao-project/bao-hypervisor/assets/24734750/54b526c2-9f5e-48b0-98bb-a260ec223af4)

_Originally posted by @Alan-Kuan in https://github.com/bao-project/bao-hypervisor/discussions/118_

**Comment by danielRep** [comment]
Hi @Alan-Kuan ,

I just reproduced the guide for the baremetal example and everything ran smoothly. Did you follow the automated make or the step-by-step guide?

**Comment by Alan-Kuan** [comment]
> Hi @Alan-Kuan ,
> 
> I just reproduced the guide for the baremetal example and everything ran smoothly. Did you follow the automated make or the step-by-step guide?

I tried both, but neither of them worked.
It just stuck at the step `tegrarcm_v2 --isapplet`, and retried after a long while.

**Comment by Alan-Kuan** [comment]
Other details:
- I built the `tos.img` inside a Docker container, and then flash the image to Jetson TX2 on the host machine.
- When I tried manually flashing the image to the board, I used [L4T Driver Package (BSP) 32.7.4](https://developer.nvidia.com/embedded/linux-tegra-r3274).

**Comment by danielRep** [comment]
Can you share the `tos.img` so I try to flash your binary in my board? I tried to the latest version of L4T (32.7.4) and it's working too.

**Comment by Alan-Kuan** [comment]
> Can you share the `tos.img` so I try to flash your binary in my board? I tried to the latest version of L4T (32.7.4) and it's working too.

Sure, here's a one-time download link to it.
https://file.io/fhCUr9R27O7H

**Comment by danielRep** [comment]
> > Can you share the `tos.img` so I try to flash your binary in my board? I tried to the latest version of L4T (32.7.4) and it's working too.
> 
> Sure, here's a one-time download link to it. https://file.io/fhCUr9R27O7H

I could flash your image without running to any issue. 
![image](https://github.com/bao-project/bao-demos/assets/19411211/f336749f-4c24-474d-b581-f08ad49223d2)
Could you check your hardware? Maybe follow the bring-up guide from Nvidia to see if everything is well configured.

**Comment by danielRep** [comment]
Okey, keep me posted so I close the issue when the problem is solved.

**Comment by Alan-Kuan** [comment]
I noticed that on [the web page of SDK Manager](https://developer.nvidia.com/sdk-manager), there's a line telling that to flash successfully, the installed package should support the host OS.

![image](https://github.com/bao-project/bao-demos/assets/24734750/5c2efd04-dbfe-46c0-a852-48b9dba116b9)

Therefore, I guessed the reason that I failed to flash `tos.img` was because my host OS is not supported by JetPack 4.x, which is the latest version of JetPack that Jetson TX2 can install.
My host OS is Ubuntu 22.04, and JetPack 4.x supports only Ubuntu 16.04 and Ubuntu 18.04.

Unfortunately, I have no machine running on either of the supported versions.
I tried running the flash tool (L4T Driver Package) inside an Ubuntu 18.04 container and a live-booted environment.
However, when I run the command `lsusb`, I found that Jetson TX2 was not recognized being in recovery mode.
I was pretty sure it was in recovery mode, as it's recognized by the original host I used.

I wonder should I use Ubuntu 18.04 to flash `tos.img` successfully, and how can I make the OS recognize the board is in recovery mode.
Is there any package that I have to install?

**Comment by danielRep** [comment]
I have flashed the TX2 under Ubuntu 22.04 (`Linux daniel-GP62M-7REX 6.2.0-39-generic #40~22.04.1-`). Did you notice if the `gen_tos_part_img` has created the `tos.img` successfully? Since I'm using Ubuntu 22.04 which comes without python2.7 support, I add to refactor the script to python3.

**Comment by Alan-Kuan** [comment]
I see. So, it should work on Ubuntu 22.04.

Yes, I noticed that it requires Python 2, so I used pyenv to install Python 2 and run the script with it.
The `tos.img` I provided yesterday was generated by this method.

Currently, I successfully flashed the JetPack 4.6.4 onto Jetson TX2.
I found that although `lsusb` didn't show the board was in recovery mode, it's actually recognized.
Therefore, I could use SDK Manager to flash the JetPack.

However, the `flash.sh` indicated that `jetson-tx2` is an invalid target board.
![screenshot](https://github.com/bao-project/bao-demos/assets/24734750/b9184eea-4dd8-44ee-b0f5-324bbc56203a)

I initially thought it was because the OS didn't recognize the board was in recovery mode, but SDK Manager did flash successfully, so it should be something else.

**Comment by Alan-Kuan** [comment]
I found the reason why `jetson-tx2` was not found.
The script utilizes relative path to work, so I should execute the script inside `Linux_for_Tegra`.

In addition, I successfully flashed `tos.img`.
This time, I switched back to run on Ubuntu 22.04.

Maybe the success was related to the upgrade of JetPack on Jetson TX2.

**Comment by danielRep** [comment]
So, you manage to flash on the docker yes? And you are testing now in Ubuntu 22.04 ?

**Comment by Alan-Kuan** [comment]
> So, you manage to flash on the docker yes? And you are testing now in Ubuntu 22.04 ?

I didn't flash on the Docker container. I did it on an Ubuntu 22.04 host.
However, I guess it will work if running the container with the flags mentioned [here](https://docs.nvidia.com/sdk-manager/docker-containers/index.html#additional-considerations).

**Comment by danielRep** [comment]
Seems now you are able to flash the board, tell us if you have successfully run the demo.

**Comment by Alan-Kuan** [comment]
> Seems now you are able to flash the board, tell us if you have successfully run the demo. 

Yes, both baremetal and FreeRTOS+Linux worked.
I think this issue can be closed.
Again. Thanks for your help!

**Comment by Alan-Kuan** [comment]
By the way, I successfully reproduced the result on another Jetson TX2 board today.
I still had to flash newer JetPack to the board first in order to successfully flash arm trusted firmware.

It looks like the first item or the third item was what made flashing arm trusted firmware work.
![Screenshot from 2024-01-11 13-53-35](https://github.com/bao-project/bao-demos/assets/24734750/ecca927a-8368-4481-8ac5-b53f4f34f727)

**Comment by danielRep** [comment]
Great @Alan-Kuan !
